### PR TITLE
Combination of (#36|#74|#75|#79|#82) + XML Comment discouraging reuse of SKSvg instances

### PR DESCRIPTION
**Pull request by Happypig375**
This is the fork I'm using now.

### CODE REVIEW

**Comment by Happypig375** [comment]
Merging depends on fixing tests of #75

**Comment by charlesroddie** [comment]
@Happypig375 can you give this PR a title and description? Assuming you intend it to be public.

**Comment by Happypig375** [comment]
Updated title to be more readable

**Comment by charlesroddie** [comment]
Hi @Happypig375 . This PR is visible in the SkiaSharp.Extended repo.
The title should say what it does.
If it's a combination of things then it's highly unlikely to get merged.
There are numbers in the title that can be converted into links to the things the numbers refer to in the main text.

**Comment by mattleibow** [comment]
Thanks for this PR, but due the the fact that this library is now deprecated, I would recommend using the far superior https://github.com/wieslawsoltes/Svg.Skia

**Pull request closed without merging**
