### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by daniel-luberda**
- https://github.com/mono/SkiaSharp.Extended/pull/74 merged
- https://github.com/mono/SkiaSharp.Extended/pull/36 merged

Fixes: 
- `style` element parsing, `style` element inside `defs` support
- fixed parsing of nested `tspan` elements (which was ignored)
- `text` support fixes
- ReadElementSize fixes
- clipPath fixes 
- fixes MeasureTextWidth throwing exception
- text stroke support, fixes for reading text styles
- CSS Fix for non lowercase class names parsing
- font shorthand support, various text handling enhancements
- initial/inherit fill/stroke support
- added gradient support for stroke
- handle 'a' tag element
- mask support fixes
- added `CancellationToken` support when parsing

### CODE REVIEW

**Comment by DennisWelu** [comment]
These look like some useful fixes. Still hoping to merge this to master?

**Comment by Happypig375** [comment]
@daniel-luberda Mind to also merge #75 and #82?

**Comment by Happypig375** [comment]
Fix tests related to gradients please

**Comment by mattleibow** [comment]
Thanks for this PR, but due the the fact that this library is now deprecated, I would recommend using the far superior https://github.com/wieslawsoltes/Svg.Skia

**Pull request closed without merging**
