### PR TITLE
Add support for text-anchor and baseline-shift

### PR DESCRIPTION
**Pull request by codedevote**
This adds support for text-anchor and baseline-shift attributes for text / tspan elements. The only limitation I see so far, is, that I can only handle the single text-anchor attribute on the enclosing text element. I ignore text-anchor attributes on tspan elements. 
I implemented this after adding clipping support (see #18), so it contains those commits as well. If that is a problem, please advice how I should prepare those commits for you.

### CODE REVIEW

**Comment by mattleibow** [comment]
Thanks for the PR, I merged the other one so you should be able to rebase/merge.

**Comment by codedevote** [comment]
I merged the upstream changes. You should be able to merge the PR now.

**Comment by codedevote** [comment]
Just wanted to know if there is anything missing that prevents this PR from getting merged?

**Comment by codedevote** [comment]
Bumping this again. @mattleibow Not sure what is missing or if this project is already going to die. Some clarification would be greatly appreciated.

**Comment by mattleibow** [comment]
Thanks for the further changes. Apologies for the very long delay. I have been working on some new features in SkiaSharp as well as a few other projects.

I have merged the changes and should be in the next release.

**Comment by codedevote** [comment]
Thanks Matthew.

**Pull request merged**
