### PR TITLE
Improved Polygon & Polylines points data parsing & display=none attribute support & rgba() / named color support

### PR DESCRIPTION
**Pull request by daniel-luberda**
- Improved Polygon & Polylines points data parsing (various formats)
- `display=none` attribute support
- rgba() & named color support

### CODE REVIEW

**Comment by CJACQUEL** [comment]
Hello, Could you update the nugget because I need this polygon modification now. It's urgent, thank you.

**Comment by mattleibow** [comment]
@daniel-luberda Thanks for this PR.

**Comment by mattleibow** [comment]
Released: https://github.com/mono/SkiaSharp.Extended/releases/tag/v1.59.1-svg

**Comment by mattleibow** [comment]
Released: https://github.com/mono/SkiaSharp.Extended/releases/tag/v1.59.1-svg

**Pull request merged**
